/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_night_before.glb 
Author: Arshan (https://sketchfab.com/yesman234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-night-before-105a415aabc14929a3bcd9088feb126d
Title: The Night Before
*/

import React, {useEffect} from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('/the_night_before.glb')
  useEffect(() => {
    // You can use hex codes, RGB, or standard CSS color names
    materials.lambert1.color.set('#9ECAE1');      // Walls/Background
    materials.Area3_D.color.set('#ff6347');       // Main accents (Tomato red)
    materials.Area2_D.color.set('#4682b4');       // Furniture/Floor (Steel blue)
    materials.aiStandardSurface2.color.set('#ffffff'); // Specific highlights
  }, [materials])
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[4.211, -20.824, 0]}>
          <mesh geometry={nodes.MonitorScreen_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.Base_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.Stand_Area3_D_0.geometry} material={materials.Area3_D} />
        </group>
        <group position={[0, -21.046, 0.184]}>
          <mesh geometry={nodes.Keyboard_Keys_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.Keyboard_Frame_Area3_D_0.geometry} material={materials.Area3_D} />
        </group>
        <group position={[0, -21.145, 0]}>
          <mesh geometry={nodes.LightSource_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.Lamp_Stand_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.Holder_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.Lamp_Base_Area3_D_0.geometry} material={materials.Area3_D} />
        </group>
        <group position={[0, -21.145, 0]}>
          <mesh geometry={nodes.pCube32_Area2_D_0.geometry} material={materials.Area2_D} position={[-86.693, 14.899, -0.674]} />
          <group position={[-86.693, 14.899, 55.48]}>
            <mesh geometry={nodes.pSphere1_Area2_D_0.geometry} material={materials.Area2_D} />
            <mesh geometry={nodes.pCube32_Area2_D_0_1.geometry} material={materials.Area2_D} />
            <mesh geometry={nodes.pSphere3_Area2_D_0.geometry} material={materials.Area2_D} />
            <mesh geometry={nodes.pSphere4_Area2_D_0.geometry} material={materials.Area2_D} />
          </group>
          <mesh geometry={nodes.pCube32_Area2_D_0_2.geometry} material={materials.Area2_D} position={[-86.693, 14.899, 111.393]} />
          <mesh geometry={nodes.TableFrame_Area2_D_0.geometry} material={materials.Area2_D} />
        </group>
        <group position={[0, 0, 27.102]}>
          <mesh geometry={nodes.Vynel_Base_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.Vynel_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.nob1_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.nob2_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.Speaker1_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.Speaker2_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube43_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube44_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube45_Area2_D_0.geometry} material={materials.Area2_D} />
        </group>
        <group position={[0, -30.002, 118.985]}>
          <mesh geometry={nodes.pCube46_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube47_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube48_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube49_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube50_Area2_D_0.geometry} material={materials.Area2_D} />
        </group>
        <group position={[0, -0.065, 0]}>
          <mesh geometry={nodes.pCube51_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube56_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube57_Area2_D_0.geometry} material={materials.Area2_D} />
          <mesh geometry={nodes.pCube54_Area2_D_0.geometry} material={materials.Area2_D} />
        </group>
        <group position={[0, 0.391, 0]}>
          <mesh geometry={nodes.pCylinder13_Area3_D_0.geometry} material={materials.Area3_D} />
          <mesh geometry={nodes.pCylinder14_Area3_D_0.geometry} material={materials.Area3_D} />
        </group>
        <mesh geometry={nodes.R_Arm_Rest_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.L_Arm_Rest_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Cusion_Connector_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Legs_Connector_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.pCube30_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.pCylinder4_Area2_D_0.geometry} material={materials.Area2_D} position={[-1.62, 0, -0.973]} />
        <mesh geometry={nodes.pCube69_Area2_D_0.geometry} material={materials.Area2_D} position={[-148.774, 0, -143.168]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.pCylinder16_Area2_D_0.geometry} material={materials.Area2_D} position={[-149.743, 0.177, -141.59]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.pCube70_Area2_D_0.geometry} material={materials.Area2_D} position={[-291.942, 0, 1.561]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.pCylinder17_Area2_D_0.geometry} material={materials.Area2_D} position={[-290.008, -0.185, 2.478]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.pCube71_Area2_D_0.geometry} material={materials.Area2_D} position={[-147.213, 0, 144.729]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.pCylinder18_Area2_D_0.geometry} material={materials.Area2_D} position={[-146.183, -0.202, 143.398]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cusion_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Base_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Front_Cusion_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.pCube18_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Mouse_Area3_D_0.geometry} material={materials.Area3_D} />
        <mesh geometry={nodes.Book_Area3_D_0.geometry} material={materials.Area3_D} />
        <mesh geometry={nodes.Side_Table_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.pCube65_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Window_1_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pCube66_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} position={[70.625, 0, 0]} />
        <mesh geometry={nodes.Book1_Area3_D_0.geometry} material={materials.Area3_D} position={[0.164, 0, 0.013]} />
        <mesh geometry={nodes.pCube67_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pCylinder15_Area3_D_0.geometry} material={materials.Area3_D} />
        <mesh geometry={nodes.pCube59_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.pCube60_Area2_D_0.geometry} material={materials.Area2_D} />
        <mesh geometry={nodes.Book15_Area3_D_0.geometry} material={materials.Area3_D} position={[-2.919, 0, 0.013]} />
        <mesh geometry={nodes.Book16_Area3_D_0.geometry} material={materials.Area3_D} position={[42.693, 97.373, 0]} rotation={[0, 0, Math.PI / 6]} />
        <mesh geometry={nodes.Book17_Area3_D_0.geometry} material={materials.Area3_D} position={[-15.953, 0.086, 0]} />
        <mesh geometry={nodes.Book18_Area3_D_0.geometry} material={materials.Area3_D} position={[-18.806, 0.086, 0]} />
        <mesh geometry={nodes.Book19_Area3_D_0.geometry} material={materials.Area3_D} position={[-21.659, 0.086, 0]} />
        <mesh geometry={nodes.Book20_Area3_D_0.geometry} material={materials.Area3_D} position={[-24.512, 0.086, 0]} />
        <mesh geometry={nodes.Book21_Area3_D_0.geometry} material={materials.Area3_D} position={[-27.365, 0.086, 0]} />
        <mesh geometry={nodes.Book22_Area3_D_0.geometry} material={materials.Area3_D} position={[-405.118, -15.797, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Book23_Area3_D_0.geometry} material={materials.Area3_D} position={[-405.118, -12.896, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Book24_Area3_D_0.geometry} material={materials.Area3_D} position={[-405.118, -9.995, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Book25_Area3_D_0.geometry} material={materials.Area3_D} position={[-405.118, -7.094, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Book26_Area3_D_0.geometry} material={materials.Area3_D} position={[-405.118, -4.193, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.pCube68_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pCube58_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Window_2_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, -122.091]} />
        <mesh geometry={nodes.Window_3_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, -245.074]} />
        <mesh geometry={nodes.pCube72_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} position={[70.625, 0, 122.557]} />
        <mesh geometry={nodes.pCube73_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} position={[70.625, 0, -122.252]} />
      </group>
    </group>
  )
}

useGLTF.preload('/the_night_before.glb')
